/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/sales/v1/orderMetrics": {
    /**
     * Returns aggregated order metrics for given interval, broken down by granularity, for given buyer type.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | .5 | 15 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrderMetrics"];
  };
}

export interface definitions {
  /** @description The response schema for the getOrderMetrics operation. */
  GetOrderMetricsResponse: {
    /** @description The payload for the getOrderMetrics operation. */
    payload?: definitions["OrderMetricsList"];
    /** @description Encountered errors for the getOrderMetrics operation. */
    errors?: definitions["ErrorList"];
  };
  /** @description A set of order metrics, each scoped to a particular time interval. */
  OrderMetricsList: definitions["OrderMetricsInterval"][];
  /** @description Contains order metrics. */
  OrderMetricsInterval: {
    /** @description The interval of time based on requested granularity (ex. Hour, Day, etc.) If this is the first or the last interval from the list, it might contain incomplete data if the requested interval doesn't align with the requested granularity (ex. request interval 2018-09-01T02:00:00Z--2018-09-04T19:00:00Z and granularity day will result in Sept 1st UTC day and Sept 4th UTC days having partial data). */
    interval: string;
    /** @description The number of units in orders based on the specified filters. */
    unitCount: number;
    /** @description The number of order items based on the specified filters. */
    orderItemCount: number;
    /** @description The number of orders based on the specified filters. */
    orderCount: number;
    /** @description The average price for an item based on the specified filters. Formula is totalSales/unitCount. */
    averageUnitPrice: definitions["Money"];
    /** @description The total ordered product sales for all orders based on the specified filters. */
    totalSales: definitions["Money"];
  };
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occured. */
    code: string;
    /** @description A message that describes the error condition in a human-readable form. */
    message: string;
    /** @description Additional details that can help the caller understand or fix the issue. */
    details?: string;
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: definitions["Error"][];
  /** @description The currency type and the amount. */
  Money: {
    /** @description Three-digit currency code. In ISO 4217 format. */
    currencyCode: string;
    /** @description The currency amount. */
    amount: definitions["Decimal"];
  };
  /** @description A decimal number with no loss of precision. Useful when precision loss is unnaceptable, as with currencies. Follows RFC7159 for number representation. */
  Decimal: string;
}

export interface operations {
  /**
   * Returns aggregated order metrics for given interval, broken down by granularity, for given buyer type.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | .5 | 15 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrderMetrics: {
    parameters: {
      query: {
        /**
         * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
         *
         * For example, ATVPDKIKX0DER indicates the US marketplace.
         */
        marketplaceIds: string[];
        /** A time interval used for selecting order metrics. This takes the form of two dates separated by two hyphens (first date is inclusive; second date is exclusive). Dates are in ISO8601 format and must represent absolute time (either Z notation or offset notation). Example: 2018-09-01T00:00:00-07:00--2018-09-04T00:00:00-07:00 requests order metrics for Sept 1st, 2nd and 3rd in the -07:00 zone. */
        interval: string;
        /** An IANA-compatible time zone for determining the day boundary. Required when specifying a granularity value greater than Hour. The granularityTimeZone value must align with the offset of the specified interval value. For example, if the interval value uses Z notation, then granularityTimeZone must be UTC. If the interval value uses an offset, then granularityTimeZone must be an IANA-compatible time zone that matches the offset. Example: US/Pacific to compute day boundaries, accounting for daylight time savings, for US/Pacific zone. */
        granularityTimeZone?: string;
        /** The granularity of the grouping of order metrics, based on a unit of time. Specifying granularity=Hour results in a successful request only if the interval specified is less than or equal to 30 days from now. For all other granularities, the interval specified must be less or equal to 2 years from now. Specifying granularity=Total results in order metrics that are aggregated over the entire interval that you specify. If the interval start and end date don’t align with the specified granularity, the head and tail end of the response interval will contain partial data. Example: Day to get a daily breakdown of the request interval, where the day boundary is defined by the granularityTimeZone. */
        granularity: "Hour" | "Day" | "Week" | "Month" | "Year" | "Total";
        /** Filters the results by the buyer type that you specify, B2B (business to business) or B2C (business to customer). Example: B2B, if you want the response to include order metrics for only B2B buyers. */
        buyerType?: "B2B" | "B2C" | "All";
        /** Filters the results by the fulfillment network that you specify, MFN (merchant fulfillment network) or AFN (Amazon fulfillment network). Do not include this filter if you want the response to include order metrics for all fulfillment networks. Example: AFN, if you want the response to include order metrics for only Amazon fulfillment network. */
        fulfillmentNetwork?: string;
        /** Specifies the day that the week starts on when granularity=Week, either Monday or Sunday. Default: Monday. Example: Sunday, if you want the week to start on a Sunday. */
        firstDayOfWeek?: "Monday" | "Sunday";
        /** Filters the results by the ASIN that you specify. Specifying both ASIN and SKU returns an error. Do not include this filter if you want the response to include order metrics for all ASINs. Example: B0792R1RSN, if you want the response to include order metrics for only ASIN B0792R1RSN. */
        asin?: string;
        /** Filters the results by the SKU that you specify. Specifying both ASIN and SKU returns an error. Do not include this filter if you want the response to include order metrics for all SKUs. Example: TestSKU, if you want the response to include order metrics for only SKU TestSKU. */
        sku?: string;
      };
    };
    responses: {
      /** OrderMetric action taken on the resource OrderMetrics. */
      200: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** 403 can be caused for reasons like Access Denied, Unauthorized, Expired Token, Invalid Signature or Resource Not Found. */
      403: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** The entity of the request is in a format not supported by the requested resource. */
      415: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** Encountered an unexpected condition which prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["GetOrderMetricsResponse"];
      };
    };
  };
}

export interface external {}
