/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/reports/2020-09-04/reports": {
    /**
     * Returns report details for the reports that match the filters that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0222 | 10 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    get: operations["getReports"];
    /**
     * Creates a report.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0167 | 15 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    post: operations["createReport"];
  };
  "/reports/2020-09-04/reports/{reportId}": {
    /**
     * Returns report details (including the reportDocumentId, if available) for the report that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 2.0 | 15 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    get: operations["getReport"];
    /**
     * Cancels the report that you specify. Only reports with processingStatus=IN_QUEUE can be cancelled. Cancelled reports are returned in subsequent calls to the getReport and getReports operations.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0222 | 10 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    delete: operations["cancelReport"];
  };
  "/reports/2020-09-04/schedules": {
    /**
     * Returns report schedule details that match the filters that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0222 | 10 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    get: operations["getReportSchedules"];
    /**
     * Creates a report schedule. If a report schedule with the same report type and marketplace IDs already exists, it will be cancelled and replaced with this one.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0222 | 10 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    post: operations["createReportSchedule"];
  };
  "/reports/2020-09-04/schedules/{reportScheduleId}": {
    /**
     * Returns report schedule details for the report schedule that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0222 | 10 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    get: operations["getReportSchedule"];
    /**
     * Cancels the report schedule that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0222 | 10 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    delete: operations["cancelReportSchedule"];
  };
  "/reports/2020-09-04/documents/{reportDocumentId}": {
    /**
     * Returns the information required for retrieving a report document's contents. This includes a presigned URL for the report document as well as the information required to decrypt the document's contents.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0167 | 15 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    get: operations["getReportDocument"];
  };
}

export interface definitions {
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: definitions["Error"][];
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition in a human-readable form. */
    message: string;
    /** @description Additional details that can help the caller understand or fix the issue. */
    details?: string;
  };
  /** @description Encryption details required for decryption of a report document's contents. */
  ReportDocumentEncryptionDetails: {
    /** @description The encryption standard required to decrypt the document contents. */
    standard: "AES";
    /** @description The vector to decrypt the document contents using Cipher Block Chaining (CBC). */
    initializationVector: string;
    /** @description The encryption key used to decrypt the document contents. */
    key: string;
  };
  Report: {
    /** @description A list of marketplace identifiers for the report. */
    marketplaceIds?: string[];
    /** @description The identifier for the report. This identifier is unique only in combination with a seller ID. */
    reportId: string;
    /** @description The report type. */
    reportType: string;
    /**
     * Format: date-time
     * @description The start of a date and time range used for selecting the data to report.
     */
    dataStartTime?: string;
    /**
     * Format: date-time
     * @description The end of a date and time range used for selecting the data to report.
     */
    dataEndTime?: string;
    /** @description The identifier of the report schedule that created this report (if any). This identifier is unique only in combination with a seller ID. */
    reportScheduleId?: string;
    /**
     * Format: date-time
     * @description The date and time when the report was created.
     */
    createdTime: string;
    /** @description The processing status of the report. */
    processingStatus:
      | "CANCELLED"
      | "DONE"
      | "FATAL"
      | "IN_PROGRESS"
      | "IN_QUEUE";
    /**
     * Format: date-time
     * @description The date and time when the report processing started, in ISO 8601 date time format.
     */
    processingStartTime?: string;
    /**
     * Format: date-time
     * @description The date and time when the report processing completed, in ISO 8601 date time format.
     */
    processingEndTime?: string;
    /** @description The identifier for the report document. Pass this into the getReportDocument operation to get the information you will need to retrieve and decrypt the report document's contents. */
    reportDocumentId?: string;
  };
  ReportList: definitions["Report"][];
  CreateReportScheduleSpecification: {
    /** @description The report type. */
    reportType: string;
    /** @description A list of marketplace identifiers for the report schedule. */
    marketplaceIds: string[];
    reportOptions?: definitions["ReportOptions"];
    /** @description One of a set of predefined ISO 8601 periods that specifies how often a report should be created. */
    period:
      | "PT5M"
      | "PT15M"
      | "PT30M"
      | "PT1H"
      | "PT2H"
      | "PT4H"
      | "PT8H"
      | "PT12H"
      | "P1D"
      | "P2D"
      | "P3D"
      | "PT84H"
      | "P7D"
      | "P14D"
      | "P15D"
      | "P18D"
      | "P30D"
      | "P1M";
    /**
     * Format: date-time
     * @description The date and time when the schedule will create its next report, in ISO 8601 date time format.
     */
    nextReportCreationTime?: string;
  };
  CreateReportSpecification: {
    reportOptions?: definitions["ReportOptions"];
    /** @description The report type. */
    reportType: string;
    /**
     * Format: date-time
     * @description The start of a date and time range, in ISO 8601 date time format, used for selecting the data to report. The default is now. The value must be prior to or equal to the current date and time. Not all report types make use of this.
     */
    dataStartTime?: string;
    /**
     * Format: date-time
     * @description The end of a date and time range, in ISO 8601 date time format, used for selecting the data to report. The default is now. The value must be prior to or equal to the current date and time. Not all report types make use of this.
     */
    dataEndTime?: string;
    /** @description A list of marketplace identifiers. The report document's contents will contain data for all of the specified marketplaces, unless the report type indicates otherwise. */
    marketplaceIds: string[];
  };
  /** @description Additional information passed to reports. This varies by report type. */
  ReportOptions: { [key: string]: string };
  /** @description Detailed information about a report schedule. */
  ReportSchedule: {
    /** @description The identifier for the report schedule. This identifier is unique only in combination with a seller ID. */
    reportScheduleId: string;
    /** @description The report type. */
    reportType: string;
    /** @description A list of marketplace identifiers. The report document's contents will contain data for all of the specified marketplaces, unless the report type indicates otherwise. */
    marketplaceIds?: string[];
    reportOptions?: definitions["ReportOptions"];
    /** @description An ISO 8601 period value that indicates how often a report should be created. */
    period: string;
    /**
     * Format: date-time
     * @description The date and time when the schedule will create its next report, in ISO 8601 date time format.
     */
    nextReportCreationTime?: string;
  };
  ReportScheduleList: definitions["ReportSchedule"][];
  CreateReportResult: {
    /** @description The identifier for the report. This identifier is unique only in combination with a seller ID. */
    reportId: string;
  };
  /** @description The response for the getReports operation. */
  GetReportsResponse: {
    /** @description The payload for the getReports operation. */
    payload?: definitions["ReportList"];
    /** @description Returned when the number of results exceeds pageSize. To get the next page of results, call getReports with this token as the only parameter. */
    nextToken?: string;
    errors?: definitions["ErrorList"];
  };
  /** @description The response for the createReport operation. */
  CreateReportResponse: {
    /** @description The payload for the createReport operation. */
    payload?: definitions["CreateReportResult"];
    errors?: definitions["ErrorList"];
  };
  /** @description The response for the cancelReport operation. */
  CancelReportResponse: {
    errors?: definitions["ErrorList"];
  };
  /** @description The response for the cancelReportSchedule operation. */
  CancelReportScheduleResponse: {
    errors?: definitions["ErrorList"];
  };
  /** @description The response for the getReport operation. */
  GetReportResponse: {
    /** @description The payload for the getReport operation. */
    payload?: definitions["Report"];
    errors?: definitions["ErrorList"];
  };
  /** @description The response for the getReportSchedules operation. */
  GetReportSchedulesResponse: {
    /** @description The payload for the getReportSchedules operation. */
    payload?: definitions["ReportScheduleList"];
    errors?: definitions["ErrorList"];
  };
  /** @description The response for the getReportSchedule operation. */
  GetReportScheduleResponse: {
    /** @description The payload for the getReportSchedule operation. */
    payload?: definitions["ReportSchedule"];
    errors?: definitions["ErrorList"];
  };
  CreateReportScheduleResult: {
    /** @description The identifier for the report schedule. This identifier is unique only in combination with a seller ID. */
    reportScheduleId: string;
  };
  /** @description The response for the createReportSchedule operation. */
  CreateReportScheduleResponse: {
    /** @description The payload for the createReportSchedule operation. */
    payload?: definitions["CreateReportScheduleResult"];
    errors?: definitions["ErrorList"];
  };
  ReportDocument: {
    /** @description The identifier for the report document. This identifier is unique only in combination with a seller ID. */
    reportDocumentId: string;
    /** @description A presigned URL for the report document. If `compressionAlgorithm` is not returned, you can download the report directly from this URL. This URL expires after 5 minutes. */
    url: string;
    encryptionDetails: definitions["ReportDocumentEncryptionDetails"];
    /** @description If the report document contents have been compressed, the compression algorithm used is returned in this property and you must decompress the report when you download. Otherwise, you can download the report directly. Refer to [Step 2. Download and decrypt the report](doc:reports-api-v2020-09-04-use-case-guide#step-2-download-and-decrypt-the-report) in the use case guide, where sample code is provided. */
    compressionAlgorithm?: "GZIP";
  };
  /** @description Response schema. */
  GetReportDocumentResponse: {
    payload?: definitions["ReportDocument"];
    errors?: definitions["ErrorList"];
  };
}

export interface operations {
  /**
   * Returns report details for the reports that match the filters that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0222 | 10 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  getReports: {
    parameters: {
      query: {
        /** A list of report types used to filter reports. When reportTypes is provided, the other filter parameters (processingStatuses, marketplaceIds, createdSince, createdUntil) and pageSize may also be provided. Either reportTypes or nextToken is required. */
        reportTypes?: string[];
        /** A list of processing statuses used to filter reports. */
        processingStatuses?: (
          | "CANCELLED"
          | "DONE"
          | "FATAL"
          | "IN_PROGRESS"
          | "IN_QUEUE"
        )[];
        /** A list of marketplace identifiers used to filter reports. The reports returned will match at least one of the marketplaces that you specify. */
        marketplaceIds?: string[];
        /** The maximum number of reports to return in a single call. */
        pageSize?: number;
        /** The earliest report creation date and time for reports to include in the response, in ISO 8601 date time format. The default is 90 days ago. Reports are retained for a maximum of 90 days. */
        createdSince?: string;
        /** The latest report creation date and time for reports to include in the response, in ISO 8601 date time format. The default is now. */
        createdUntil?: string;
        /** A string token returned in the response to your previous request. nextToken is returned when the number of results exceeds the specified pageSize value. To get the next page of results, call the getReports operation and include this token as the only parameter. Specifying nextToken with any other parameters will cause the request to fail. */
        nextToken?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["GetReportsResponse"];
      };
    };
  };
  /**
   * Creates a report.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0167 | 15 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  createReport: {
    parameters: {
      body: {
        body: definitions["CreateReportSpecification"];
      };
    };
    responses: {
      /** Success. */
      202: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["CreateReportResponse"];
      };
    };
  };
  /**
   * Returns report details (including the reportDocumentId, if available) for the report that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 2.0 | 15 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  getReport: {
    parameters: {
      path: {
        /** The identifier for the report. This identifier is unique only in combination with a seller ID. */
        reportId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["GetReportResponse"];
      };
    };
  };
  /**
   * Cancels the report that you specify. Only reports with processingStatus=IN_QUEUE can be cancelled. Cancelled reports are returned in subsequent calls to the getReport and getReports operations.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0222 | 10 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  cancelReport: {
    parameters: {
      path: {
        /** The identifier for the report. This identifier is unique only in combination with a seller ID. */
        reportId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["CancelReportResponse"];
      };
    };
  };
  /**
   * Returns report schedule details that match the filters that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0222 | 10 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  getReportSchedules: {
    parameters: {
      query: {
        /** A list of report types used to filter report schedules. */
        reportTypes: string[];
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["GetReportSchedulesResponse"];
      };
    };
  };
  /**
   * Creates a report schedule. If a report schedule with the same report type and marketplace IDs already exists, it will be cancelled and replaced with this one.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0222 | 10 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  createReportSchedule: {
    parameters: {
      body: {
        body: definitions["CreateReportScheduleSpecification"];
      };
    };
    responses: {
      /** Success. */
      201: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["CreateReportScheduleResponse"];
      };
    };
  };
  /**
   * Returns report schedule details for the report schedule that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0222 | 10 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  getReportSchedule: {
    parameters: {
      path: {
        /** The identifier for the report schedule. This identifier is unique only in combination with a seller ID. */
        reportScheduleId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["GetReportScheduleResponse"];
      };
    };
  };
  /**
   * Cancels the report schedule that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0222 | 10 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  cancelReportSchedule: {
    parameters: {
      path: {
        /** The identifier for the report schedule. This identifier is unique only in combination with a seller ID. */
        reportScheduleId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["CancelReportScheduleResponse"];
      };
    };
  };
  /**
   * Returns the information required for retrieving a report document's contents. This includes a presigned URL for the report document as well as the information required to decrypt the document's contents.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0167 | 15 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  getReportDocument: {
    parameters: {
      path: {
        /** The identifier for the report document. */
        reportDocumentId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** The request's Content-Type header is invalid. */
      415: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["GetReportDocumentResponse"];
      };
    };
  };
}

export interface external {}
