/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface paths {
    "/notifications/v1/subscriptions/{notificationType}": {
        /**
         * Returns information about subscriptions of the specified notification type. You can use this API to get subscription information when you do not have a subscription identifier.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        get: operations["getSubscription"];
        /**
         * Creates a subscription for the specified notification type to be delivered to the specified destination. Before you can subscribe, you must first create the destination by calling the createDestination operation.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        post: operations["createSubscription"];
    };
    "/notifications/v1/subscriptions/{notificationType}/{subscriptionId}": {
        /**
         * Returns information about a subscription for the specified notification type. The getSubscriptionById API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        get: operations["getSubscriptionById"];
        /**
         * Deletes the subscription indicated by the subscription identifier and notification type that you specify. The subscription identifier can be for any subscription associated with your application. After you successfully call this operation, notifications will stop being sent for the associated subscription. The deleteSubscriptionById API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        delete: operations["deleteSubscriptionById"];
    };
    "/notifications/v1/destinations": {
        /**
         * Returns information about all destinations. The getDestinations API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        get: operations["getDestinations"];
        /**
         * Creates a destination resource to receive notifications. The createDestination API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        post: operations["createDestination"];
    };
    "/notifications/v1/destinations/{destinationId}": {
        /**
         * Returns information about the destination that you specify. The getDestination API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        get: operations["getDestination"];
        /**
         * Deletes the destination that you specify. The deleteDestination API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
         *
         * **Usage Plan:**
         *
         * | Rate (requests per second) | Burst |
         * | ---- | ---- |
         * | 1 | 5 |
         *
         * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         */
        delete: operations["deleteDestination"];
    };
}
export interface definitions {
    /**
     * @description Additional information passed to the subscription to control the processing of notifications. For example, you can use an eventFilter to customize your subscription to send notifications for only the specified marketplaceId's, or select the aggregation time period at which to send notifications (e.g. limit to one notification every five minutes for high frequency notifications). The specific features available vary depending on the notificationType.
     *
     * This feature is limited to specific notificationTypes and is currently only supported by the ANY_OFFER_CHANGED notificationType.
     */
    ProcessingDirective: {
        /** @description A notificationType specific filter. */
        eventFilter?: definitions["EventFilter"];
    };
    /** @description A notificationType specific filter. This object contains all of the currently available filters and properties that you can use to define a notificationType specific filter. */
    EventFilter: definitions["AggregationFilter"] & definitions["MarketplaceFilter"] & {
        /** @description An eventFilterType value that is supported by the specific notificationType. This is used by the subscription service to determine the type of event filter. Refer to the section of the [Notifications Use Case Guide](doc:notifications-api-v1-use-case-guide) that describes the specific notificationType to determine if an eventFilterType is supported. */
        eventFilterType: string;
    };
    /** @description Use this event filter to customize your subscription to send notifications for only the specified marketplaceId's. */
    MarketplaceFilter: {
        marketplaceIds?: definitions["MarketplaceIds"];
    };
    /** @description A list of marketplace identifiers to subscribe to (e.g. ATVPDKIKX0DER). To receive notifications in every marketplace, do not provide this list. */
    MarketplaceIds: string[];
    /** @description Use this filter to select the aggregation time period at which to send notifications (e.g. limit to one notification every five minutes for high frequency notifications). */
    AggregationFilter: {
        aggregationSettings?: definitions["AggregationSettings"];
    };
    /** @description A container that holds all of the necessary properties to configure the aggregation of notifications. */
    AggregationSettings: {
        /** @description The supported time period to use to perform marketplace-ASIN level aggregation. */
        aggregationTimePeriod: definitions["AggregationTimePeriod"];
    };
    /** @description The supported aggregation time periods. For example, if FiveMinutes is the value chosen, and 50 price updates occur for an ASIN within 5 minutes, Amazon will send only two notifications; one for the first event, and then a subsequent notification 5 minutes later with the final end state of the data. The 48 interim events will be dropped. */
    AggregationTimePeriod: "FiveMinutes" | "TenMinutes";
    /** @description Represents a subscription to receive notifications. */
    Subscription: {
        /** @description The subscription identifier generated when the subscription is created. */
        subscriptionId: string;
        /** @description The version of the payload object to be used in the notification. */
        payloadVersion: string;
        /** @description The identifier for the destination where notifications will be delivered. */
        destinationId: string;
        processingDirective?: definitions["ProcessingDirective"];
    };
    /** @description The response schema for the createSubscription operation. */
    CreateSubscriptionResponse: {
        /** @description The payload for the createSubscription operation. */
        payload?: definitions["Subscription"];
        /** @description One or more unexpected errors occurred during the createSubscription operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description The request schema for the createSubscription operation. */
    CreateSubscriptionRequest: {
        /** @description The version of the payload object to be used in the notification. */
        payloadVersion?: string;
        /** @description The identifier for the destination where notifications will be delivered. */
        destinationId?: string;
        processingDirective?: definitions["ProcessingDirective"];
    };
    /** @description The response schema for the getSubscriptionById operation. */
    GetSubscriptionByIdResponse: {
        /** @description The payload for the getSubscriptionById operation. */
        payload?: definitions["Subscription"];
        /** @description An unexpected condition occurred during the getSubscriptionById operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description The response schema for the getSubscription operation. */
    GetSubscriptionResponse: {
        /** @description The payload for the getSubscription operation. */
        payload?: definitions["Subscription"];
        /** @description One or more unexpected errors occurred during the getSubscription operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description The response schema for the deleteSubscriptionById operation. */
    DeleteSubscriptionByIdResponse: {
        /** @description An unexpected condition occurred during the deleteSubscriptionById operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description A list of destinations. */
    DestinationList: definitions["Destination"][];
    /** @description Represents a destination created when you call the createDestination operation. */
    Destination: {
        /** @description The developer-defined name for this destination. */
        name: string;
        /** @description The destination identifier generated when you created the destination. */
        destinationId: string;
        /** @description The resource that will receive notifications associated with this destination. */
        resource: definitions["DestinationResource"];
    };
    /** @description The destination resource types. */
    DestinationResource: {
        /** @description An Amazon Simple Queue Service (SQS) queue destination. */
        sqs?: definitions["SqsResource"];
        /** @description An Amazon EventBridge destination. */
        eventBridge?: definitions["EventBridgeResource"];
    };
    /** @description The information required to create a destination resource. Applications should use one resource type (sqs or eventBridge) per destination. */
    DestinationResourceSpecification: {
        /** @description The information required to create an Amazon Simple Queue Service (SQS) queue destination. */
        sqs?: definitions["SqsResource"];
        /** @description The information required to create an Amazon EventBridge destination. */
        eventBridge?: definitions["EventBridgeResourceSpecification"];
    };
    /** @description The information required to create an Amazon Simple Queue Service (Amazon SQS) queue destination. */
    SqsResource: {
        /** @description The Amazon Resource Name (ARN) associated with the SQS queue. */
        arn: string;
    };
    /** @description The information required to create an Amazon EventBridge destination. */
    EventBridgeResourceSpecification: {
        /** @description The AWS region in which you will be receiving the notifications. */
        region: string;
        /** @description The identifier for the AWS account that is responsible for charges related to receiving notifications. */
        accountId: string;
    };
    /** @description Represents an Amazon EventBridge destination. */
    EventBridgeResource: {
        /** @description The name of the partner event source associated with the destination. */
        name: string;
        /** @description The AWS region in which you receive the notifications. For AWS regions that are supported in Amazon EventBridge, see https://docs.aws.amazon.com/general/latest/gr/ev.html. */
        region: string;
        /** @description The identifier for the AWS account that is responsible for charges related to receiving notifications. */
        accountId: string;
    };
    /** @description The request schema for the createDestination operation. */
    CreateDestinationRequest: {
        /** @description The information required to create a destination resource. Applications should use one resource type (sqs or eventBridge) per destination. */
        resourceSpecification: definitions["DestinationResourceSpecification"];
        /** @description A developer-defined name to help identify this destination. */
        name: string;
    };
    /** @description The response schema for the createDestination operation. */
    CreateDestinationResponse: {
        /** @description The payload for the createDestination operation. */
        payload?: definitions["Destination"];
        /** @description One or more unexpected errors occurred during the createDestination operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description The response schema for the getDestination operation. */
    GetDestinationResponse: {
        /** @description The payload for the getDestination operation. */
        payload?: definitions["Destination"];
        /** @description One or more unexpected errors occurred during the getDestination operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description The response schema for the getDestinations operation. */
    GetDestinationsResponse: {
        /** @description The payload for the getDestinations operation. */
        payload?: definitions["DestinationList"];
        /** @description One or more unexpected errors occurred during the getDestinations operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description The response schema for the deleteDestination operation. */
    DeleteDestinationResponse: {
        /** @description One or more unexpected errors occurred during the deleteDestination operation. */
        errors?: definitions["ErrorList"];
    };
    /** @description A list of error responses returned when a request is unsuccessful. */
    ErrorList: definitions["Error"][];
    /** @description Error response returned when the request is unsuccessful. */
    Error: {
        /** @description An error code that identifies the type of error that occurred. */
        code: string;
        /** @description A message that describes the error condition in a human-readable form. */
        message: string;
        /** @description Additional details that can help the caller understand or fix the issue. */
        details?: string;
    };
}
export interface parameters {
    /**
     * @description The type of notification.
     *
     *  For more information about notification types, see [the Notifications API Use Case Guide](doc:notifications-api-v1-use-case-guide).
     */
    NotificationType: string;
}
export interface operations {
    /**
     * Returns information about subscriptions of the specified notification type. You can use this API to get subscription information when you do not have a subscription identifier.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    getSubscription: {
        parameters: {
            path: {
                /**
                 * The type of notification.
                 *
                 *  For more information about notification types, see [the Notifications API Use Case Guide](doc:notifications-api-v1-use-case-guide).
                 */
                notificationType: parameters["NotificationType"];
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
        };
    };
    /**
     * Creates a subscription for the specified notification type to be delivered to the specified destination. Before you can subscribe, you must first create the destination by calling the createDestination operation.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    createSubscription: {
        parameters: {
            body: {
                body: definitions["CreateSubscriptionRequest"];
            };
            path: {
                /**
                 * The type of notification.
                 *
                 *  For more information about notification types, see [the Notifications API Use Case Guide](doc:notifications-api-v1-use-case-guide).
                 */
                notificationType: parameters["NotificationType"];
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** The resource specified conflicts with the current state. */
            409: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["CreateSubscriptionResponse"];
            };
        };
    };
    /**
     * Returns information about a subscription for the specified notification type. The getSubscriptionById API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    getSubscriptionById: {
        parameters: {
            path: {
                /** The identifier for the subscription that you want to get. */
                subscriptionId: string;
                /**
                 * The type of notification.
                 *
                 *  For more information about notification types, see [the Notifications API Use Case Guide](doc:notifications-api-v1-use-case-guide).
                 */
                notificationType: parameters["NotificationType"];
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["GetSubscriptionResponse"];
            };
            /** The resource specified conflicts with the current state. */
            409: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["GetSubscriptionByIdResponse"];
            };
        };
    };
    /**
     * Deletes the subscription indicated by the subscription identifier and notification type that you specify. The subscription identifier can be for any subscription associated with your application. After you successfully call this operation, notifications will stop being sent for the associated subscription. The deleteSubscriptionById API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    deleteSubscriptionById: {
        parameters: {
            path: {
                /** The identifier for the subscription that you want to delete. */
                subscriptionId: string;
                /**
                 * The type of notification.
                 *
                 *  For more information about notification types, see [the Notifications API Use Case Guide](doc:notifications-api-v1-use-case-guide).
                 */
                notificationType: parameters["NotificationType"];
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** The resource specified conflicts with the current state. */
            409: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["DeleteSubscriptionByIdResponse"];
            };
        };
    };
    /**
     * Returns information about all destinations. The getDestinations API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    getDestinations: {
        parameters: {};
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** The resource specified conflicts with the current state. */
            409: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["GetDestinationsResponse"];
            };
        };
    };
    /**
     * Creates a destination resource to receive notifications. The createDestination API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    createDestination: {
        parameters: {
            body: {
                body: definitions["CreateDestinationRequest"];
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** The resource specified conflicts with the current state. */
            409: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["CreateDestinationResponse"];
            };
        };
    };
    /**
     * Returns information about the destination that you specify. The getDestination API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    getDestination: {
        parameters: {
            path: {
                /** The identifier generated when you created the destination. */
                destinationId: string;
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** The resource specified conflicts with the current state. */
            409: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["GetDestinationResponse"];
            };
        };
    };
    /**
     * Deletes the destination that you specify. The deleteDestination API is grantless. For more information, see [Grantless operations](doc:grantless-operations) in the Selling Partner API Developer Guide.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 5 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    deleteDestination: {
        parameters: {
            path: {
                /** The identifier for the destination that you want to delete. */
                destinationId: string;
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** The resource specified conflicts with the current state. */
            409: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** The request size exceeded the maximum accepted size. */
            413: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["DeleteDestinationResponse"];
            };
        };
    };
}
export interface external {
}
