/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface paths {
    "/vendor/directFulfillment/transactions/v1/transactions/{transactionId}": {
        /**
         * Returns the status of the transaction indicated by the specified transactionId.
         *
         * **Usage Plans:**
         *
         * | Plan type | Rate (requests per second) | Burst |
         * | ---- | ---- | ---- |
         * |Default| 10 | 10 |
         * |Selling partner specific| Variable | Variable |
         *
         * The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
         */
        get: operations["getTransactionStatus"];
        parameters: {};
    };
}
export interface definitions {
    /** @description The response schema for the getTransactionStatus operation. */
    GetTransactionResponse: {
        payload?: definitions["TransactionStatus"];
        errors?: definitions["ErrorList"];
    };
    /** @description The payload for the getTransactionStatus operation. */
    TransactionStatus: {
        transactionStatus?: definitions["Transaction"];
    };
    /** @description The transaction status details. */
    Transaction: {
        /** @description The unique identifier sent in the 'transactionId' field in response to the post request of a specific transaction. */
        transactionId: string;
        /** @description Current processing status of the transaction. */
        status: "Failure" | "Processing" | "Success";
        /** @description Error code and message for the failed transaction. Only available when transaction status is 'Failure'. */
        errors?: definitions["ErrorList"];
    };
    /** @description A list of error responses returned when a request is unsuccessful. */
    ErrorList: definitions["Error"][];
    /** @description Error response returned when the request is unsuccessful. */
    Error: {
        /** @description An error code that identifies the type of error that occurred. */
        code: string;
        /** @description A message that describes the error condition. */
        message: string;
        /** @description Additional details that can help the caller understand or fix the issue. */
        details?: string;
    };
}
export interface operations {
    /**
     * Returns the status of the transaction indicated by the specified transactionId.
     *
     * **Usage Plans:**
     *
     * | Plan type | Rate (requests per second) | Burst |
     * | ---- | ---- | ---- |
     * |Default| 10 | 10 |
     * |Selling partner specific| Variable | Variable |
     *
     * The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    getTransactionStatus: {
        parameters: {
            path: {
                /** Previously returned in the response to the POST request of a specific transaction. */
                transactionId: string;
            };
        };
        responses: {
            /** Success. */
            200: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** Request has missing or invalid parameters and cannot be parsed. */
            400: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
            401: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
            403: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** The resource specified does not exist. */
            404: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** The request payload is in an unsupported format. */
            415: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** The frequency of requests was greater than allowed. */
            429: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** An unexpected condition occurred that prevented the server from fulfilling the request. */
            500: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
            /** Temporary overloading or maintenance of the server. */
            503: {
                headers: {};
                schema: definitions["GetTransactionResponse"];
            };
        };
    };
}
export interface external {
}
