/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/batches/products/pricing/2022-05-01/offer/featuredOfferExpectedPrice": {
    /**
     * Returns the set of responses that correspond to the batched list of up to 40 requests defined in the request body. The response for each successful (HTTP status code 200) request in the set includes the computed listing price at or below which a seller can expect to become the featured offer (before applicable promotions). This is called the featured offer expected price (FOEP). Featured offer is not guaranteed, because competing offers may change, and different offers may be featured based on other factors, including fulfillment capabilities to a specific customer. The response to an unsuccessful request includes the available error text.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.033 | 1 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    post: operations["getFeaturedOfferExpectedPriceBatch"];
  };
}

export interface definitions {
  /** @description The request body for the getFeaturedOfferExpectedPriceBatch operation. */
  GetFeaturedOfferExpectedPriceBatchRequest: {
    requests?: definitions["FeaturedOfferExpectedPriceRequestList"];
  };
  /** @description A batched list of featured offer expected price requests. */
  FeaturedOfferExpectedPriceRequestList: definitions["FeaturedOfferExpectedPriceRequest"][];
  /** @description An individual featured offer expected price request for a particular SKU. */
  FeaturedOfferExpectedPriceRequest: definitions["BatchRequest"] &
    definitions["FeaturedOfferExpectedPriceRequestParams"];
  /** @description The parameters for an individual request. */
  FeaturedOfferExpectedPriceRequestParams: {
    marketplaceId: definitions["MarketplaceId"];
    sku: definitions["Sku"];
  };
  /** @description The response schema for the getFeaturedOfferExpectedPriceBatch operation. */
  GetFeaturedOfferExpectedPriceBatchResponse: {
    responses?: definitions["FeaturedOfferExpectedPriceResponseList"];
  };
  /** @description A batched list of featured offer expected price responses. */
  FeaturedOfferExpectedPriceResponseList: definitions["FeaturedOfferExpectedPriceResponse"][];
  FeaturedOfferExpectedPriceResponse: definitions["BatchResponse"] & {
    /** @description Use these request parameters to map the response back to the request. */
    request: definitions["FeaturedOfferExpectedPriceRequestParams"];
    body?: definitions["FeaturedOfferExpectedPriceResponseBody"];
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  Errors: {
    /** @description One or more unexpected errors occurred during the operation. */
    errors: definitions["ErrorList"];
  };
  /** @description The featured offer expected price response data for a requested SKU. */
  FeaturedOfferExpectedPriceResponseBody: {
    /** @description Metadata that identifies the target offer for which the featured offer expected price result data was computed. */
    offerIdentifier: definitions["OfferIdentifier"];
    /** @description The featured offer expected price results for the requested target offer. */
    featuredOfferExpectedPriceResults?: definitions["FeaturedOfferExpectedPriceResultList"];
    /** @description The errors that occurred if the operation was not successful (HTTP status code non-200). */
    errors?: definitions["ErrorList"];
  };
  /** @description A list of featured offer expected price results for the requested offer. */
  FeaturedOfferExpectedPriceResultList: definitions["FeaturedOfferExpectedPriceResult"][];
  /** @description The featured offer expected price result data for the requested offer. */
  FeaturedOfferExpectedPriceResult: {
    featuredOfferExpectedPrice?: definitions["FeaturedOfferExpectedPrice"];
    /** @description The status of the featured offer expected price computation. Possible values include VALID_FOEP, NO_COMPETING_OFFER, OFFER_NOT_ELIGIBLE, OFFER_NOT_FOUND. */
    resultStatus: string;
    /** @description The offer that will likely be the featured offer if the target offer is priced above its featured offer expected price. If the target offer is currently the featured offer, this property will be different than currentFeaturedOffer. */
    competingFeaturedOffer?: definitions["FeaturedOffer"];
    /** @description The offer that is currently the featured offer. If the target offer is not currently featured, this property will be equal to competingFeaturedOffer. */
    currentFeaturedOffer?: definitions["FeaturedOffer"];
  };
  /** @description The item price at or below which the target offer may be featured. */
  FeaturedOfferExpectedPrice: {
    /** @description A computed listing price at or below which a seller can expect to become the featured offer (before applicable promotions). */
    listingPrice: definitions["MoneyType"];
    /** @description The number of Amazon Points offered with the purchase of an item, and their monetary value. */
    points?: definitions["Points"];
  };
  FeaturedOffer: {
    /** @description An offer identifier used to identify the merchant of the featured offer. Since this may not belong to the requester, the SKU field will be omitted. */
    offerIdentifier: definitions["OfferIdentifier"];
    /** @description The item condition. */
    condition?: definitions["Condition"];
    /** @description The current active price of the offer. */
    price?: definitions["Price"];
  };
  /** @description A mapping of additional HTTP headers to send/receive for an individual request within a batch. */
  HttpHeaders: { [key: string]: string };
  /** @description The HTTP status line associated with the response to an individual request within a batch. For more information, consult [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html). */
  HttpStatusLine: {
    /** @description The HTTP response Status-Code. */
    statusCode?: number;
    /** @description The HTTP response Reason-Phase. */
    reasonPhrase?: string;
  };
  /** @description Additional HTTP body information associated with an individual request within a batch. */
  HttpBody: { [key: string]: unknown };
  /** @description The HTTP method associated with an individual request within a batch. */
  HttpMethod: "GET" | "PUT" | "PATCH" | "DELETE" | "POST";
  /** @description The common properties for individual requests within a batch. */
  BatchRequest: {
    /** @description The URI associated with an individual request within a batch. For FeaturedOfferExpectedPrice, this should be '/products/pricing/2022-05-01/offer/featuredOfferExpectedPrice'. */
    uri: string;
    method: definitions["HttpMethod"];
    body?: definitions["HttpBody"];
    headers?: definitions["HttpHeaders"];
  };
  /** @description The common properties for responses to individual requests within a batch. */
  BatchResponse: {
    headers: definitions["HttpHeaders"];
    status: definitions["HttpStatusLine"];
  };
  /** @description Identifies an offer from a particular seller on an ASIN. */
  OfferIdentifier: {
    /** @description A marketplace identifier. */
    marketplaceId: definitions["MarketplaceId"];
    /** @description The seller identifier for the offer. */
    sellerId?: string;
    /** @description The seller stock keeping unit (SKU) of the item. This will only be present for the target offer, which belongs to the requesting seller. */
    sku?: string;
    /** @description The Amazon identifier for the item. */
    asin: definitions["Asin"];
    /** @description The fulfillment type for the offer. */
    fulfillmentType?: definitions["FulfillmentType"];
  };
  MoneyType: {
    /** @description The currency code in ISO 4217 format. */
    currencyCode?: string;
    /** @description The monetary value. */
    amount?: number;
  };
  Price: {
    /** @description The listing price of the item excluding any promotions. */
    listingPrice: definitions["MoneyType"];
    /** @description The shipping cost of the product. Note that the shipping cost is not always available. */
    shippingPrice?: definitions["MoneyType"];
    /** @description The number of Amazon Points offered with the purchase of an item, and their monetary value. */
    points?: definitions["Points"];
  };
  Points: {
    /**
     * Format: int32
     * @description The number of points.
     */
    pointsNumber?: number;
    /** @description The monetary value of the points. */
    pointsMonetaryValue?: definitions["MoneyType"];
  };
  /** @description Indicates whether the item is fulfilled by Amazon or by the seller (merchant). */
  FulfillmentType: "AFN" | "MFN";
  /** @description A marketplace identifier. Specifies the marketplace for which data is returned. */
  MarketplaceId: string;
  /** @description The seller SKU of the item. */
  Sku: string;
  /** @description The condition of the item. */
  Condition: "New" | "Used" | "Collectible" | "Refurbished" | "Club";
  /** @description The Amazon Standard Identification Number (ASIN) of the item. */
  Asin: string;
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: definitions["Error"][];
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition. */
    message: string;
    /** @description Additional information that can help the caller understand or fix the issue. */
    details?: string;
  };
}

export interface operations {
  /**
   * Returns the set of responses that correspond to the batched list of up to 40 requests defined in the request body. The response for each successful (HTTP status code 200) request in the set includes the computed listing price at or below which a seller can expect to become the featured offer (before applicable promotions). This is called the featured offer expected price (FOEP). Featured offer is not guaranteed, because competing offers may change, and different offers may be featured based on other factors, including fulfillment capabilities to a specific customer. The response to an unsuccessful request includes the available error text.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.033 | 1 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
   */
  getFeaturedOfferExpectedPriceBatch: {
    parameters: {
      body: {
        getFeaturedOfferExpectedPriceBatchRequestBody: definitions["GetFeaturedOfferExpectedPriceBatchRequest"];
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["GetFeaturedOfferExpectedPriceBatchResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["Errors"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["Errors"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: definitions["Errors"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: definitions["Errors"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["Errors"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["Errors"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["Errors"];
      };
    };
  };
}

export interface external {}
