/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/fba/inbound/v1/eligibility/itemPreview": {
    /**
     * This operation gets an eligibility preview for an item that you specify. You can specify the type of eligibility preview that you want (INBOUND or COMMINGLING). For INBOUND previews, you can specify the marketplace in which you want to determine the item's eligibility.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 1 |
     *
     * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
     */
    get: operations["getItemEligibilityPreview"];
  };
}

export interface definitions {
  /** @description The response schema for the getItemEligibilityPreview operation. */
  GetItemEligibilityPreviewResponse: {
    /** @description The payload for the getItemEligibilityPreview operation. */
    payload?: definitions["ItemEligibilityPreview"];
    /** @description An unexpected condition occurred during the GetItemEligibilityPreview operation. */
    errors?: definitions["ErrorList"];
  };
  /** @description The response object which contains the ASIN, marketplaceId if required, eligibility program, the eligibility status (boolean), and a list of ineligibility reason codes. */
  ItemEligibilityPreview: {
    /** @description The ASIN for which eligibility was determined. */
    asin: string;
    /** @description The marketplace for which eligibility was determined. */
    marketplaceId?: string;
    /** @description The program for which eligibility was determined. */
    program: "INBOUND" | "COMMINGLING";
    /** @description Indicates if the item is eligible for the program. */
    isEligibleForProgram: boolean;
    /** @description Potential Ineligibility Reason Codes. */
    ineligibilityReasonList?: (
      | "FBA_INB_0004"
      | "FBA_INB_0006"
      | "FBA_INB_0007"
      | "FBA_INB_0008"
      | "FBA_INB_0009"
      | "FBA_INB_0010"
      | "FBA_INB_0011"
      | "FBA_INB_0012"
      | "FBA_INB_0013"
      | "FBA_INB_0014"
      | "FBA_INB_0015"
      | "FBA_INB_0016"
      | "FBA_INB_0017"
      | "FBA_INB_0018"
      | "FBA_INB_0019"
      | "FBA_INB_0034"
      | "FBA_INB_0035"
      | "FBA_INB_0036"
      | "FBA_INB_0037"
      | "FBA_INB_0038"
      | "FBA_INB_0050"
      | "FBA_INB_0051"
      | "FBA_INB_0053"
      | "FBA_INB_0055"
      | "FBA_INB_0056"
      | "FBA_INB_0059"
      | "FBA_INB_0065"
      | "FBA_INB_0066"
      | "FBA_INB_0067"
      | "FBA_INB_0068"
      | "FBA_INB_0095"
      | "FBA_INB_0097"
      | "FBA_INB_0098"
      | "FBA_INB_0099"
      | "FBA_INB_0100"
      | "FBA_INB_0103"
      | "FBA_INB_0104"
      | "FBA_INB_0197"
      | "UNKNOWN_INB_ERROR_CODE"
    )[];
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: definitions["Error"][];
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition in a human-readable form. */
    message?: string;
    /** @description Additional information that can help the caller understand or fix the issue. */
    details?: string;
  };
}

export interface operations {
  /**
   * This operation gets an eligibility preview for an item that you specify. You can specify the type of eligibility preview that you want (INBOUND or COMMINGLING). For INBOUND previews, you can specify the marketplace in which you want to determine the item's eligibility.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 1 | 1 |
   *
   * For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.
   */
  getItemEligibilityPreview: {
    parameters: {
      query: {
        /** The identifier for the marketplace in which you want to determine eligibility. Required only when program=INBOUND. */
        marketplaceIds?: string[];
        /** The ASIN of the item for which you want an eligibility preview. */
        asin: string;
        /** The program that you want to check eligibility against. */
        program: "INBOUND" | "COMMINGLING";
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
      /** 403 can be caused for reasons like Access Denied, Unauthorized, Expired Token, Invalid Signature or Resource Not Found. */
      403: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
      /** Encountered an unexpected condition which prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: definitions["GetItemEligibilityPreviewResponse"];
      };
    };
  };
}

export interface external {}
